// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frmjdxziwwlfpgevszga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZybWpkeHppd3dsZnBnZXZzemdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTQ1ODMsImV4cCI6MjA2ODE3MDU4M30.9EUl0YeXsNg2kpkcKjwWWgNKhucz41CZsGknXGq5XyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});